### ISSUE TITLE
Style the home page

### ISSUE THREAD

**Issue by jmejia** [plato721/givenget#17]
* Include a moving image for the background of the top of the page with a button for "Give" and "Get"

* Add a section titled "Success Stories" to bring attention to those that have been helped

* Add a section for "Generous Givers" to highlight  those that have contributed goods and services.

**Comment by plato721** [comment]
@jmejia you want a carousel image on the homepage? (re: moving image)

**Comment by jmejia** [comment]
@plato721 Haha... Great question. What I meant was "emotionally moving image". I wasn't very clear. If you want to have it rotate, go for it. I'm not requiring it right now, though.

**Comment by plato721** [comment]
oh okay @jmejia awesome. i was like i don't remember rotation being mentioned. but i do remember the emotional bit. thanks.
