### ISSUE TITLE
Adjusting the quantity of an item in the cart

### ISSUE THREAD

**Issue by jmejia** [plato721/givenget#22]
Background: My cart has an item in it

      As a visitor
      When I visit "/cart"
      Then I should see my item with a quantity of 1
      And when I increase the quantity
      Then my current page should be '/cart'
      And that item's quantity should reflect the increase
      And the subtotal for that item should increase
      And the total for the cart should match that increase

      And when I decrease the quantity
      Then my current page should be '/cart'
      And that item's quantity should reflect the decrease
      And the subtotal for that item should decrease
      And the total for the cart should match that decrease

**Comment by plato721** [comment]
This is working.. adds one or subtracts one based on clicking appropriate button. We may tweak this but it does allow adjustment of quantity within the cart, as requested.
