### ISSUE TITLE
Checking out

### ISSUE THREAD

**Issue by jmejia** [plato721/givenget#26]
Background: An existing user and a cart with items

      As a visitor
      When I visit "/cart"
      And I click "Checkout"
      Then I should be required to login

      When I am logged in
      And I visit "/cart"
      And I click "Checkout"
      Then the order should be placed
      And my current page should be "/orders"
      And I should see a message "Order was successfully placed"
      And I should see the order I just placed in a table

**Comment by plato721** [comment]
The login requirement will pend George's integrations but I can work on the order creation without that.

**Comment by plato721** [comment]
Styling could improve but this story is complete
